services:
  - type: web
    name: yatraawb
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://yatrawb.netlify.app
      - key: PORT
        value: 5001
    healthCheckPath: /
    autoDeploy: true